import './globals.css'
import { Inter } from 'next/font/google';
import Navbar from '../components/navbar/page';
import { Alert } from '../components/alert'
const inter = Inter({ subsets: ['latin'] })
import ReduxProvider from "../store/withStore";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Alert />
        <ReduxProvider>
          {children}
        </ReduxProvider>

      </body>
    </html>
  )
}
